language: python

sudo: false

python:
  - "2.7"

install:
  - "pip install pep8"
  - "pip install azure"
  - "pip install docopt"
  - "pip install APScheduler"
  - "pip install pyliblzma"

script: make pep8 test
